- id: '1527922079178'
  alias: Paul Bathroom Button
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.wall_switch_left_bathroom
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - service: script.shower_paul
- id: '1527925880014'
  alias: Play/Pause Ensuite
  trigger:
  - event_data:
      click_type: both
      entity_id: binary_sensor.wall_switch_both_bathroom
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - data:
      entity_id: media_player.bathroom
    service: media_player.media_play_pause
- id: '1528768127918'
  alias: 'Sonos: Switch Loungeroom amp when active'
  trigger:
  - entity_id: media_player.lounge
    from: paused
    platform: state
    to: playing
  condition: []
  action:
  - data:
      entity_id: automation.receiver_update_last_state
    service: automation.turn_off
  - data:
      entity_id: media_player.receiver
    service: media_player.turn_on
  - timeout: 00:00:10
    wait_template: '{{ is_state(''media_player.receiver'', ''on'') }}'
  - data:
      entity_id: media_player.receiver
      source: Video2
    service: media_player.select_source
  - data:
      entity_id: media_player.receiver
      volume_level: 0.825
    service: media_player.volume_set
- id: '1528777053684'
  alias: 'Receiver: update last state'
  trigger:
  - entity_id: media_player.receiver
    platform: state
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.attributes.source not in ["Sonos", "video2_cbl_sat"]  }}'
  action:
  - data:
      value_template: '{{ states("media_player.receiver") }}'
      variable: receiver_last_state
    service: variable.set_variable
  - data:
      value_template: '{% if is_state("media_player.receiver", "on") -%}{{ state_attr("media_player.receiver",
        "source") | regex_replace("_.*", "") | regex_replace("^video", "Video") }}{%-
        else -%}{{ states("variable.receiver_last_source") }}{%- endif %}'
      variable: receiver_last_source
    service: variable.set_variable
  - data:
      value_template: '{% if is_state("media_player.receiver", "on") -%}{{ state_attr("media_player.receiver",
        "volume_level") }}{%- else -%}{{ states("variable.receiver_last_volume") }}{%-
        endif %}'
      variable: receiver_last_volume
    service: variable.set_variable
- id: '1528780901218'
  alias: 'Sonos: Switch loungeroom back after finished'
  trigger:
  - entity_id: media_player.lounge
    from: playing
    platform: state
    to: paused
  condition: []
  action:
  - data_template:
      entity_id: media_player.receiver
      volume_level: '{{ states("variable.receiver_last_volume") }}'
    service: media_player.volume_set
  - data_template:
      entity_id: media_player.receiver
      source: '{{ states("variable.receiver_last_source") }}'
    service: media_player.select_source
  - data_template:
      entity_id: '{% if is_state("variable.receiver_last_state", "off") -%}media_player.receiver{%-
        else -%}dummy.dummy{%- endif -%}'
    service: media_player.turn_off
  - delay:
      seconds: 20
  - data:
      entity_id: automation.receiver_update_last_state
    service: automation.turn_on
- id: '1546759967727'
  alias: Bedside Button
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_bedside
    event_type: xiaomi_aqara.click
    platform: event
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_bedside_right
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - data:
      entity_id:
      - light.bedside_left
      - light.bedside_right
    service: light.toggle
- id: '1546762544388'
  alias: Bedside Button Double Click
  trigger:
  - event_data:
      click_type: double
      entity_id: binary_sensor.switch_bedside
    event_type: xiaomi_aqara.click
    platform: event
  - event_data:
      click_type: double
      entity_id: binary_sensor.switch_bedside_right
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - service: light.turn_off
  - service: script.sonos_sleep
- id: '1546980843431'
  alias: Paul Arrive Home
  trigger:
  - entity_id: device_tracker.paul_coral
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: group.kids_presence
    state: not_home
  action:
  - service: light.turn_on
  - service: script.sonos_get_home
- id: '1546984412841'
  alias: Paul Leave Home
  trigger:
  - entity_id: device_tracker.paul_coral
    platform: state
    from: home
    to: not_home
    for:
      minutes: 10
  condition: []
  action:
  - service: media_player.media_pause
  - service: light.turn_off
