- id: '1527922079178'
  alias: Paul Bathroom Button
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.wall_switch_left_bathroom
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - service: script.shower_paul
- id: '1527925880014'
  alias: Play/Pause Ensuite
  trigger:
  - event_data:
      click_type: both
      entity_id: binary_sensor.wall_switch_both_bathroom
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - data:
      entity_id: media_player.bathroom
    service: media_player.media_play_pause
- id: '1528768127918'
  alias: 'Sonos: Switch Loungeroom amp when active'
  trigger:
  - entity_id: media_player.lounge
    from: paused
    platform: state
    to: playing
  condition: []
  action:
  - data:
      entity_id: automation.receiver_update_last_state
    service: automation.turn_off
  - data:
      entity_id: media_player.receiver
    service: media_player.turn_on
  - timeout: 00:00:10
    wait_template: '{{ is_state(''media_player.receiver'', ''on'') }}'
  - data:
      entity_id: media_player.receiver
      source: Video2
    service: media_player.select_source
  - data:
      entity_id: media_player.receiver
      volume_level: 0.825
    service: media_player.volume_set
- id: '1528777053684'
  alias: 'Receiver: update last state'
  trigger:
  - entity_id: media_player.receiver
    platform: state
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.attributes.source not in ["Sonos", "video2_cbl_sat"]  }}'
  action:
  - data:
      value_template: '{{ states("media_player.receiver") }}'
      entity_id: var.receiver_last_state
    service: var.set
  - data:
      value_template: '{% if is_state("media_player.receiver", "on") -%}{{ state_attr("media_player.receiver",
        "source") | regex_replace("_.*", "") | regex_replace("^video", "Video") }}{%-
        else -%}{{ states("variable.receiver_last_source") }}{%- endif %}'
      entity_id: var.receiver_last_source
    service: var.set
  - data:
      value_template: '{% if is_state("media_player.receiver", "on") -%}{{ state_attr("media_player.receiver",
        "volume_level") }}{%- else -%}{{ states("variable.receiver_last_volume") }}{%-
        endif %}'
      entity_id: receiver_last_volume
    service: var.set
- id: '1528780901218'
  alias: 'Sonos: Switch loungeroom back after finished'
  trigger:
  - entity_id: media_player.lounge
    from: playing
    platform: state
    to: paused
  condition: []
  action:
  - data_template:
      entity_id: media_player.receiver
      volume_level: '{{ states("var.receiver_last_volume") }}'
    service: media_player.volume_set
  - data_template:
      entity_id: media_player.receiver
      source: '{{ states("var.receiver_last_source") }}'
    service: media_player.select_source
  - data_template:
      entity_id: '{% if is_state("var.receiver_last_state", "off") -%}media_player.receiver{%-
        else -%}dummy.dummy{%- endif -%}'
    service: media_player.turn_off
  - delay:
      seconds: 20
  - data:
      entity_id: automation.receiver_update_last_state
    service: automation.turn_on
- id: '1546759967727'
  alias: Bedside Button
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_bedside
    event_type: xiaomi_aqara.click
    platform: event
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_bedside_right
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - data: {}
    service: light.toggle
    target:
      entity_id: light.bedside_lamps
  mode: single
- id: '1546762544388'
  alias: Bedside Button Double Click
  trigger:
  - event_data:
      click_type: double
      entity_id: binary_sensor.switch_bedside
    event_type: xiaomi_aqara.click
    platform: event
  - event_data:
      click_type: double
      entity_id: binary_sensor.switch_bedside_right
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - service: light.turn_off
  - service: script.sonos_sleep
- id: '1546980843431'
  alias: Paul Arrive Home
  trigger:
  - entity_id: device_tracker.paul_coral
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: group.kids_presence
    state: not_home
  action:
  - service: light.turn_on
  - service: script.sonos_get_home
- id: '1546984412841'
  alias: Paul Leave Home
  trigger:
  - entity_id: device_tracker.paul_coral
    platform: state
    from: home
    to: not_home
    for:
      minutes: 10
  condition: []
  action:
  - service: media_player.media_pause
  - service: light.turn_off
- id: '1621316877856'
  alias: 'Tasmota Discovery: Aroma Diffuser 1'
  description: ''
  use_blueprint:
    path: tasmota/discovery-tuya_diffuser_fan_and_error_sensor.yaml
    input:
      name: diffuser1
      topic: tasmota_1229CD
      mac_address: 4C:11:AE:12:29:CD
- id: '1621318073028'
  alias: 'Tasmota Discovery: Aroma Diffuser 2'
  description: ''
  use_blueprint:
    path: tasmota/discovery-tuya_diffuser_fan_and_error_sensor.yaml
    input:
      name: diffuser2
      topic: tasmota_1222E9
      mac_address: 4C:11:AE:12:22:E9
- id: '1622424964423'
  alias: Update Cat Flap State from Cloud
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.cat_flap_cloud_state
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.cat_flap_state
    data:
      option: '{{ states("sensor.cat_flap_cloud_state") }}'
  mode: single
- id: '1622457098699'
  alias: Push Cat Flap State to Cloud
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.cat_flap_state
  condition:
  - condition: template
    value_template: '{{ states(''input_select.cat_flap_state'') != states(''sensor.cat_flap_cloud_state'')
      }}'
  action:
  - service: system_log.write
    data:
      message: Firing due to change to {{ states('input_select.cat_flap_state') }}
        vs cloud state {{ states('sensor.cat_flap_cloud_state') }}
  - service: script.set_cat_flap_state
    data:
      target_state: '{{ states("input_select.cat_flap_state") }}'
  mode: single
- id: '1622457601269'
  alias: Keep cats in Bedroom at Night
  description: ''
  trigger:
  - platform: time
    at: '22:00'
  condition: []
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.cat_flap_state
    data:
      option: keep_in_bedroom
  mode: single
- id: '1622457637235'
  alias: Let cats out in morning
  description: ''
  trigger:
  - platform: time
    at: 05:00
  condition: []
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.cat_flap_state
    data:
      option: all_unlocked
  mode: single
- id: '1622631147055'
  alias: Pause Overnight Music
  description: ''
  trigger:
  - platform: time
    at: 05:00
  condition: []
  action:
  - service: media_player.media_pause
    target:
      entity_id:
      - media_player.master_bedroom
      - media_player.guest_room
  mode: single
- id: '1622693720246'
  alias: Doorbell Reaction
  description: ''
  trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      click_type: single
      entity_id: binary_sensor.front_doorbell_button
  condition: []
  action:
  - service: yeelight.set_color_flow_scene
    data:
      entity_id: light.yeelight_livingroom
      count: 2
      action: recover
      transitions:
      - HSVTransition:
        - 180
        - 100
        - 100
        - 80
      - HSVTransition:
        - 180
        - 100
        - 250
        - 1
  mode: single
- id: '1622697978346'
  alias: test both
  description: ''
  trigger:
  - device_id: b9bb1e104f88289e6cd8a17ce2b3eeb4
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: both_buttons
  condition: []
  action:
  - service: logbook.log
    data:
      name: aa
      message: boo double
  mode: single
- id: '1622699855727'
  alias: Bedside Button (new)
  description: ''
  trigger:
  - device_id: 2543c7facf8ff8c81c60072e55aa7c67
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id: light.bedside_lamps
  mode: single
- id: '1622700041681'
  alias: '**TEST* button'
  description: ''
  trigger:
  - device_id: 937ffa395d66f28b51bde7ff03f3e77e
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id: light.yeelight_livingroom
    data:
      kelvin: 3200
      brightness_pct: 80
  mode: single
- id: '1622700231745'
  alias: '**TEST* button 2'
  description: ''
  trigger:
  - device_id: 937ffa395d66f28b51bde7ff03f3e77e
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: remote_button_double_press
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.yeelight_livingroom
    data:
      effect: LSD
  mode: single
