- id: '1527922079178'
  alias: Paul Bathroom Button
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.wall_switch_left_bathroom
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - service: script.shower_paul
- id: '1527925880014'
  alias: Play/Pause Ensuite
  trigger:
  - event_data:
      click_type: both
      entity_id: binary_sensor.wall_switch_both_bathroom
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - data:
      entity_id: media_player.bathroom
    service: media_player.media_play_pause
- id: '1528768127918'
  alias: 'Sonos: Switch Loungeroom amp when active'
  trigger:
  - entity_id: media_player.lounge
    from: paused
    platform: state
    to: playing
  condition: []
  action:
  - data:
      entity_id: automation.receiver_update_last_state
    service: automation.turn_off
  - data:
      entity_id: media_player.receiver
    service: media_player.turn_on
  - timeout: 00:00:10
    wait_template: '{{ is_state(''media_player.receiver'', ''on'') }}'
  - data:
      entity_id: media_player.receiver
      source: Video2
    service: media_player.select_source
  - data:
      entity_id: media_player.receiver
      volume_level: 0.825
    service: media_player.volume_set
- id: '1528777053684'
  alias: 'Receiver: update last state'
  trigger:
  - entity_id: media_player.receiver
    platform: state
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.attributes.source not in ["Sonos", "video2_cbl_sat"]  }}'
  action:
  - data:
      value_template: '{{ states("media_player.receiver") }}'
      entity_id: var.receiver_last_state
    service: var.set
  - data:
      value_template: '{% if is_state("media_player.receiver", "on") -%}{{ state_attr("media_player.receiver",
        "source") | regex_replace("_.*", "") | regex_replace("^video", "Video") }}{%-
        else -%}{{ states("variable.receiver_last_source") }}{%- endif %}'
      entity_id: var.receiver_last_source
    service: var.set
  - data:
      value_template: '{% if is_state("media_player.receiver", "on") -%}{{ state_attr("media_player.receiver",
        "volume_level") }}{%- else -%}{{ states("variable.receiver_last_volume") }}{%-
        endif %}'
      entity_id: receiver_last_volume
    service: var.set
- id: '1528780901218'
  alias: 'Sonos: Switch loungeroom back after finished'
  trigger:
  - entity_id: media_player.lounge
    from: playing
    platform: state
    to: paused
  condition: []
  action:
  - data_template:
      entity_id: media_player.receiver
      volume_level: '{{ states("var.receiver_last_volume") }}'
    service: media_player.volume_set
  - data_template:
      entity_id: media_player.receiver
      source: '{{ states("var.receiver_last_source") }}'
    service: media_player.select_source
  - data_template:
      entity_id: '{% if is_state("var.receiver_last_state", "off") -%}media_player.receiver{%-
        else -%}dummy.dummy{%- endif -%}'
    service: media_player.turn_off
  - delay:
      seconds: 20
  - data:
      entity_id: automation.receiver_update_last_state
    service: automation.turn_on
- id: '1546762544388'
  alias: Bedside Button Left Double Click (Paul Sleep)
  trigger:
  - device_id: 937ffa395d66f28b51bde7ff03f3e77e
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: remote_button_double_press
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id: master_bedroom
  - service: script.sonos_sleep
  mode: single
- id: '1546980843431'
  alias: Paul Arrive Home
  trigger:
  - entity_id: device_tracker.paul_raven
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: group.kids_presence
    state: not_home
  action:
  - service: light.turn_on
  - service: script.sonos_get_home
- id: '1546984412841'
  alias: Paul Leave Home
  trigger:
  - entity_id: device_tracker.paul_raven
    platform: state
    from: home
    to: not_home
    for:
      minutes: 10
  condition: []
  action:
  - service: media_player.media_pause
  - service: light.turn_off
- id: '1621316877856'
  alias: 'Tasmota Discovery: Aroma Diffuser 1'
  description: ''
  use_blueprint:
    path: tasmota/discovery-tuya_diffuser_fan_and_error_sensor.yaml
    input:
      name: diffuser1
      topic: tasmota_1229CD
      mac_address: 4C:11:AE:12:29:CD
- id: '1621318073028'
  alias: 'Tasmota Discovery: Aroma Diffuser 2'
  description: ''
  use_blueprint:
    path: tasmota/discovery-tuya_diffuser_fan_and_error_sensor.yaml
    input:
      name: diffuser2
      topic: tasmota_1222E9
      mac_address: 4C:11:AE:12:22:E9
- id: '1622424964423'
  alias: Update Cat Flap State from Cloud
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.cat_flap_cloud_state
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.cat_flap_state
    data:
      option: '{{ states("sensor.cat_flap_cloud_state") }}'
  mode: single
- id: '1622457098699'
  alias: Push Cat Flap State to Cloud
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.cat_flap_state
  condition:
  - condition: template
    value_template: '{{ states(''input_select.cat_flap_state'') != states(''sensor.cat_flap_cloud_state'')
      }}'
  action:
  - service: system_log.write
    data:
      message: Firing due to change to {{ states('input_select.cat_flap_state') }}
        vs cloud state {{ states('sensor.cat_flap_cloud_state') }}
  - service: script.set_cat_flap_state
    data:
      target_state: '{{ states("input_select.cat_flap_state") }}'
  mode: single
- id: '1622457601269'
  alias: Keep cats in Bedroom at Night
  description: ''
  trigger:
  - platform: time
    at: '22:00'
  condition: []
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.cat_flap_state
    data:
      option: keep_in_office
  mode: single
- id: '1622457637235'
  alias: Let cats out in morning
  description: ''
  trigger:
  - platform: time
    at: 05:00
  condition: []
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.cat_flap_state
    data:
      option: all_unlocked
  mode: single
- id: '1622631147055'
  alias: Pause Overnight Music
  description: ''
  trigger:
  - platform: time
    at: 05:00
  condition: []
  action:
  - service: media_player.media_pause
    target:
      entity_id:
      - media_player.master_bedroom
      - media_player.guest_room
  mode: single
- id: '1622693720246'
  alias: Doorbell Reaction
  description: ''
  trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      click_type: single
      entity_id: binary_sensor.front_doorbell_button
  condition: []
  action:
  - service: yeelight.set_color_flow_scene
    data:
      entity_id: light.yeelight_livingroom
      count: 2
      action: recover
      transitions:
      - HSVTransition:
        - 180
        - 100
        - 100
        - 80
      - HSVTransition:
        - 180
        - 100
        - 250
        - 1
  mode: single
- id: '1622697978346'
  alias: test both
  description: ''
  trigger:
  - device_id: b9bb1e104f88289e6cd8a17ce2b3eeb4
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: both_buttons
  condition: []
  action:
  - service: logbook.log
    data:
      name: aa
      message: boo double
  mode: single
- id: '1622699855727'
  alias: Bedside Buttons click (Toggle Lamps)
  description: ''
  trigger:
  - device_id: 2543c7facf8ff8c81c60072e55aa7c67
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  - device_id: 937ffa395d66f28b51bde7ff03f3e77e
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id: light.bedside_lamps
    data: {}
  mode: single
- id: '1622700041681'
  alias: '**TEST* button'
  description: ''
  trigger:
  - device_id: 937ffa395d66f28b51bde7ff03f3e77e
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id: light.yeelight_livingroom
    data:
      kelvin: 3200
      brightness_pct: 80
  mode: single
- id: '1622700231745'
  alias: '**TEST* button 2'
  description: ''
  trigger:
  - device_id: 937ffa395d66f28b51bde7ff03f3e77e
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: remote_button_double_press
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.yeelight_livingroom
    data:
      effect: LSD
  mode: single
- id: '1624282422729'
  alias: Telegram test
  description: ''
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: /hi
  condition: []
  action:
  - service: telegram_bot.send_message
    data:
      message: Hi yourself, {{ trigger.event.data["from_first"] }}!
      target: '{{ trigger.event.data.chat_id }}'
  mode: single
- id: '1624101614357'
  alias: Toggle Outside Lights
  description: ''
  trigger:
  - device_id: ab450a7b3d8039f7716d894b38bf16e6
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id: light.outside_globes
  mode: single
- id: '1624283044736'
  alias: Telegram Home
  description: ''
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: /digest
  condition: []
  action:
  - service: telegram_bot.send_message
    data:
      message: "\U0001F321️ Living Room Temp = {{ states(\"sensor.living_room_temperature\"\
        ) }}°C \n\U0001F321 Outside Temp = {{ states(\"sensor.temperature_outside\"\
        ) }}°C\n\U0001F324 Weather = {{ states(\"sensor.lilyfield_short_text_0\")\
        \ }} (tomorrow {{ states(\"sensor.lilyfield_short_text_1\") }})\n\U0001F327\
        ️ Chance of rain = {{ states(\"sensor.lilyfield_rain_chance_0\") }}% (tomorrow\
        \ {{ states(\"sensor.lilyfield_rain_chance_1\") }}%)"
      target: '{{ trigger.event.data.chat_id }}'
  mode: single
- id: '1624427657811'
  alias: Office Opple 6-button
  description: ''
  use_blueprint:
    path: Jarne_Roussard/aqara-opple-6-buttons-for-zha.yaml
    input:
      remote: 95b075d60c583891acfd8ad2a67d898d
      button_top_left_single_press:
      - service: light.toggle
        target:
          entity_id: light.yeelight_office
      button_top_left_triple_press:
      - service: fan.toggle
        target:
          entity_id: fan.office_diffuser
      button_middle_left_single_press:
      - service: media_player.volume_down
        target:
          entity_id: media_player.office
      button_middle_left_double_press:
      - service: media_player.media_previous_track
        target:
          entity_id: media_player.office
      button_middle_right_single_press:
      - service: media_player.volume_up
        target:
          entity_id: media_player.office
      button_middle_right_double_press:
      - service: media_player.media_next_track
        target:
          entity_id: media_player.office
      button_bottom_left_single_press:
      - type: brightness_decrease
        device_id: 8a466522fced3aa1009b180e4be85ada
        entity_id: light.yeelight_office
        domain: light
      button_bottom_right_single_press:
      - type: brightness_increase
        device_id: 8a466522fced3aa1009b180e4be85ada
        entity_id: light.yeelight_office
        domain: light
      button_bottom_right_hold_release: []
      button_bottom_left_hold_in:
      - service: light.turn_off
        target:
          entity_id: light.yeelight_office
      button_bottom_right_hold_in:
      - service: light.turn_on
        data:
          brightness_pct: 100
          color_temp: 299
        target:
          entity_id: light.yeelight_office
      button_middle_left_triple_press: []
      button_middle_left_hold_in:
      - service: media_player.media_play_pause
        target:
          entity_id: media_player.office
      button_middle_right_hold_in:
      - service: sonos.unjoin
        target:
          entity_id: media_player.office
      - service: media_player.clear_playlist
        target:
          entity_id: media_player.office
      - service: media_player.shuffle_set
        data:
          shuffle: true
        target:
          entity_id: media_player.office
      - service: script.sonos_play_matching
        data:
          entity_id: media_player.office
          match: \U0001F42E
      button_bottom_right_double_press:
      - service: light.turn_on
        target:
          entity_id: light.yeelight_office
        data:
          color_temp: '{{ min(state_attr("light.yeelight_office", "color_temp")|int
            + 20, state_attr("light.yeelight_office", "max_mireds")|int) }}'
      button_bottom_left_double_press:
      - service: light.turn_on
        target:
          entity_id: light.yeelight_office
        data:
          color_temp: '{{ max(state_attr("light.yeelight_office", "color_temp")|int
            - 20, state_attr("light.yeelight_office", "min_mireds")|int) }}'
- id: '1624503867808'
  alias: Toggle Party Lights
  description: ''
  trigger:
  - device_id: ab450a7b3d8039f7716d894b38bf16e6
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: remote_button_double_press
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id: light.flux_party
    data:
      effect: colorloop
  mode: single
- id: '1628031664645'
  alias: Office Light Switch
  description: ''
  use_blueprint:
    path: carlosmesquita/zha-xiaomi-mijia-round-wireless-switch-wxkg01lm-lumi-sensor-switch.yaml
    input:
      mijia_round_switch: 563998aaa5579f08a3dcbcac1e8a2505
      remote_button_short_press:
      - service: light.toggle
        target:
          entity_id: light.yeelight_office
- id: '1629256775832'
  alias: ⚡ Dishwasher Running
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.dishwasher_power
    above: '50'
  condition:
  - condition: state
    entity_id: input_select.dishwasher_state
    state: Idle
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.dishwasher_state
    data:
      option: Running
  mode: single
- id: '1629257243979'
  alias: ⚡ Dishwasher Finished
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.dishwasher_power
    below: '5'
  condition:
  - condition: state
    entity_id: input_select.dishwasher_state
    state: Running
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.dishwasher_state
    data:
      option: Finished
  mode: single
- id: '1633580036748'
  alias: 'Blinds: Close at Sunset'
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - device_id: ef916ad229bd58ca7fc4b96119cfadd4
    domain: cover
    entity_id: cover.living_room_blind
    type: set_position
  mode: single
- id: '1633601876342'
  alias: 'Blinds: Open in the Morning'
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  condition: []
  action:
  - device_id: ef916ad229bd58ca7fc4b96119cfadd4
    domain: cover
    entity_id: cover.living_room_blind
    type: set_position
    position: 100
  mode: single
- id: '1634176799507'
  alias: Turn Selfie Light on when meeting starts
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.cow_macbookpro_in_meeting
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    target:
      device_id: 245c4e4fae5052b2ae415bbda80bb475
    data:
      brightness: 255
      color_name: white
  mode: single
- id: '1634179680814'
  alias: Turn Selfie Light off when meeting ends
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.cow_macbookpro_in_meeting
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.office_ring_light
  mode: single
- id: '1638313007824'
  alias: Office Magic Cube
  description: ''
  use_blueprint:
    path: Mikkelmoeller/aqara-magic-cube-zha-51-actions.yaml
    input:
      remote: 32aee9b615dfbf3b485c18093910afed
      rotate_right:
      - service: media_player.volume_up
        target:
          entity_id: media_player.office
      rotate_left:
      - service: media_player.volume_down
        target:
          entity_id: media_player.office
      knock_any_side: true
      cube_knock_any:
      - service: media_player.media_play_pause
        target:
          entity_id: media_player.office
      cube_flip_180:
      - service: media_player.media_previous_track
        target:
          entity_id: media_player.office
      flip_180: true
      flip_90: true
      cube_flip_90:
      - service: media_player.media_next_track
        target:
          entity_id: media_player.office
      cube_shake:
      - service: script.sonos_play_matching
        data:
          entity_id: media_player.office
          match: \U0001F42E
