version: "3.7"
services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:2023.1
    network_mode: host
    volumes:
      - .:/config
      - /etc/localtime:/etc/localtime:ro 
    restart: unless-stopped
