version: "3.7"
services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:2023.4
    network_mode: host
    volumes:
      - .:/config
      - /etc/localtime:/etc/localtime:ro 
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
