version: "3.7"
services:
  home-assistant:
    image: homeassistant/home-assistant:2022.12
    network_mode: host
    volumes:
      - /home/paul/docker-data/ha-config:/config
      - /etc/localtime:/etc/localtime:ro 
    restart: unless-stopped
