title: The Dairy

background: radial-gradient(navy, skyblue)
# Exclude entities from "Unused entities" view
excluded_entities:
  - binary_sensor.switch_bedside
  - binary_sensor.wall_switch_both_bathroom
  - binary_sensor.wall_switch_left_bathroom
  - binary_sensor.wall_switch_right_bathroom
  - group.all_automations
  - group.all_devices
  - group.all_lights
  - group.all_scripts
  - group.all_switches
  - group.unassigned
  - script.sonos_play_non_matching
  - script.sonos_play_matching
  - script.sonos_ungroup_and_play
  - sensor.battery_paul
  - sensor.lastfm_cowanfamily
  - switch.plug_bedroom_left
  - switch.plug_bedroom_right
  - switch.plug_beerfridge
views:
  - title: Overview
    path: overview
    cards:
      - type: entity-filter
        entities:
          - group.paul_presence
          - group.kids_presence
        state_filter:
          - 'home'
        card:
          type: glance
          title: Currently home
      - type: entities
        entities:
          - input_boolean.guest_mode
      - type: gauge
        entity:
          - sensor.battery_paul
  - title: Living Room
    icon: mdi:sofa
    path: living
    cards:
      - type: media-control
        entity: media_player.kitchen_2
      - type: media-control
        entity: media_player.kitchen_display
      - type: media-control
        entity: media_player.living_room
      - type: media-control
        entity: media_player.living_room_tv
      - type: entities
        entities:
          - binary_sensor.front_door
  - title: Bedroom
    icon: mdi:bed-empty
    path: bedroom
    cards:
      - type: media-control
        entity: media_player.master_bedroom_2
      - type: media-control
        entity: media_player.master_bedroom_speaker
      - type: horizontal-stack
        cards:
        - type: light
          entity: light.gateway_light
        - type: light
          entity: light.bedside_lamps
      - type: entities
        entities:
          - sun.sun
          - sensor.illumination_gateway
          - binary_sensor.motion_sensor_bedroom
  - title: Balcony
    icon: mdi:pine-tree
    path: balcony
    cards:
      - type: glance
        entities:
          - sun.sun
          - sensor.moon
          - sensor.season
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
          - type: sensor
            entity: sensor.temperature_beerfridge
            detail: 2
            graph: line
          - type: sensor
            entity: sensor.beerfridge_power
            graph: line
            detail: 2
            icon: mdi:flash
        - type: glance
          entities:
            - entity: sensor.pressure_beerfridge
              name: 
            - entity: sensor.humidity_beerfridge
              name: 
            - entity: sensor.beerfridge_power_consumed
              name: 
              icon: mdi:flash
  - title: Bathroom
    icon: mdi:shower
    path: bathroom
    cards:
      - type: media-control
        entity: media_player.bathroom
      - type: entity-button
        entity: script.shower_paul
  - title: Kids room
    icon: mdi:account-multiple
    path: kids
    cards:
      - type: media-control
        entity: media_player.kids_bedroom
  - title: Configuration
    icon: mdi:settings
    path: settings
    cards:
      - type: entities
        title: Individual Lights
        entities:
          - light.bedside_lamp_left
          - light.bedside_lamp_right
      - type: glance
        title: Automation Triggers
        entities:
          - automation.bedside_button
          - automation.bedside_button_double_click
      - type: glance
        title: Device Trackers
        entities:
          - device_tracker.paul_crosshatch
          - device_tracker.paul_pixel3xl
          - device_tracker.google_maps_107519494119268402848
          - device_tracker.oppof1s
          - device_tracker.galaxys7a
          - device_tracker.pixel
      - type: glance
        title: Power
        icon: mdi:flash
        entities:
          - sensor.bedroom_left_power
          - sensor.bedroom_left_power_consumed
          - sensor.bedroom_right_power
          - sensor.bedroom_right_power_consumed
          - sensor.beerfridge_power
          - sensor.beerfridge_power_consumed
