title: The Dairy

background: radial-gradient(navy, skyblue)
# Exclude entities from "Unused entities" view
excluded_entities:
  - binary_sensor.switch_bedside
  - binary_sensor.switch_bedside_right
  - binary_sensor.wall_switch_both_bathroom
  - binary_sensor.wall_switch_left_bathroom
  - binary_sensor.wall_switch_right_bathroom
  - group.all_automations
  - group.all_devices
  - group.all_lights
  - group.all_scripts
  - group.all_switches
  - group.unassigned
  - script.sonos_play_non_matching
  - script.sonos_play_matching
  - script.sonos_ungroup_and_play
  - sensor.battery_paul
  - sensor.lastfm_cowanfamily
  - switch.plug_bedroom_left
  - switch.plug_bedroom_right
  - switch.plug_beerfridge
views:
  - title: Overview
    path: overview
    cards:
      - type: entity-filter
        entities:
          - person.paul
          - person.dorothy
          - group.kids_presence
        state_filter:
          - 'home'
        card:
          type: glance
          title: Currently home
      - type: entities
        entities:
          - binary_sensor.pet_tabitha
          - binary_sensor.pet_tamara
      - type: entities
        entities:
          - input_boolean.guest_mode
      - type: gauge
        entity:
          - sensor.battery_paul
      - type: sensor
        entity: sensor.temperature_livingroom
        detail: 2
        graph: line
      - type: sensor
        entity: sensor.humidity_livingroom
        detail: 2
        graph: line
      - type: weather-forecast
        entity: weather.dark_sky
      - type: media-control
        entity: media_player.home_group
  - title: Living Room
    icon: mdi:sofa
    path: living
    cards:
      - type: media-control
        entity: media_player.living_room
      - type: media-control
        entity: media_player.living_room_tv
      - type: media-control
        entity: media_player.receiver
      - type: media-control
        entity: media_player.living_room_sonos_cast
      - type: entities
        entities:
          - binary_sensor.front_door_open
          - lock.front_door
          - sensor.front_door_operator
  - title: Kitchen
    icon: mdi:fridge-outline
    path: kitchen
    cards:
      - type: media-control
        entity: media_player.kitchen
      - type: entities
        entities:
        - switch.diffuser_fan
        - light.diffuser_light
  - title: Bedroom
    icon: mdi:bed-empty
    path: bedroom
    cards:
      - type: media-control
        entity: media_player.master_bedroom
      - type: media-control
        entity: media_player.master_bedroom_mini
      - type: horizontal-stack
        cards:
        - type: entities
          show_header_toggle: false
          entities:
          - entity: light.bedside_lamps
          - type: 'custom:rgb-light-card'
            entity: light.bedside_lamps
            colors:
              - rgb_color:
                  - 255
                  - 255
                  - 255
                brightness: 100
                transition: 1
              - rgb_color:
                  - 234
                  - 136
                  - 140
                brightness: 255
                transition: 1
              - rgb_color:
                  - 251
                  - 180
                  - 139
                brightness: 200
                transition: 1
              - rgb_color:
                  - 136
                  - 198
                  - 237
                brightness: 150
                transition: 1
              - rgb_color:
                  - 140
                  - 231
                  - 185
                brightness: 100
                transition: 1

      - type: entities
        entities:
          - sun.sun
          - binary_sensor.motion_sensor_bedroom
  - title: Outside
    icon: mdi:pine-tree
    path: outside
    cards:
      - type: 'custom:sun-card'
      - type: weather-forecast
        entity: weather.lilyfield
      - type: glance
        entities:
          - sun.sun
          - sensor.moon
          - sensor.season
      - type: media-control
        entity: media_player.outside
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
          - type: sensor
            entity: sensor.temperature_beerfridge
            detail: 2
            graph: line
          - type: sensor
            entity: sensor.beerfridge_power
            graph: line
            detail: 2
            icon: mdi:flash
        - type: glance
          entities:
            - entity: sensor.pressure_beerfridge
              name: 
            - entity: sensor.humidity_beerfridge
              name: 
            - entity: sensor.beerfridge_power_consumed
              name: 
              icon: mdi:flash
      - type: thermostat
        entity: climate.beer_fridge
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.outside_globes
          - type: vertical-stack
            cards:
            - type: light
              entity: light.flux_fairy
              name: Fairy Lights
            - type: 'custom:rgb-light-card'
              entity: light.flux_fairy
              colors: !include flux_colors.yaml
          - type: vertical-stack
            cards:
            - type: light
              entity: light.flux_party
              name: Party Lights
            - type: 'custom:rgb-light-card'
              entity: light.flux_party
              colors: !include flux_colors.yaml

  - title: Bathroom
    icon: mdi:shower
    path: bathroom
    cards:
      - type: media-control
        entity: media_player.bathroom
      - type: media-control
        entity: media_player.bathroom_display
      - type: entity-button
        entity: script.shower_paul
  - title: Guest room
    icon: mdi:bunk-bed
    path: guest
    cards:
      - type: media-control
        entity: media_player.guest_room
      - type: horizontal-stack
        cards:
        - type: light
          entity: light.guest_room_right
        - type: light
          entity: light.gateway_light
      - type: sensor
        entity: sensor.illumination_gateway
        graph: line
  - title: Paul Office
    icon: mdi:desk
    path: office
    cards:
      - type: media-control
        entity: media_player.office
      - type: entities
        entities:
        - switch.diffuser_fan_2
        - light.diffuser_light_2
  - title: Dot Office
    icon: mdi:chair-rolling
    path: dot
    cards:
      - type: media-control
        entity: media_player.bathroom
  - title: Configuration
    icon: mdi:cog
    path: settings
    cards:
      - type: entities
        title: Individual Lights
        entities:
          - light.bedside_left
          - light.bedside_right
      - type: glance
        title: Automation Triggers
        entities:
          - automation.bedside_button
          - automation.bedside_button_double_click
          - automation.paul_arrive_home
          - automation.paul_leave_home
          - automation.paul_bathroom_button
      - type: glance
        title: Device Trackers
        entities:
          - device_tracker.paul_coral
          # - device_tracker.google_maps_107519494119268402848
          - device_tracker.oppof1s
          - device_tracker.galaxys7a
          - device_tracker.pixel
          - device_tracker.dotties_iphone
      - type: glance
        title: Power
        icon: mdi:flash
        entities:
          - sensor.bedroom_left_power
          - sensor.bedroom_left_power_consumed
          - sensor.bedroom_right_power
          - sensor.bedroom_right_power_consumed
          - sensor.beerfridge_power
          - sensor.beerfridge_power_consumed
      - type: 'custom:battery-state-card'
        title: Battery State
        sort_by_level: asc
        tap_action: more-info
        filter:
          include:
            - name: entity_id
              value: '*_battery_level'
            - name: attributes.device_class
              value: battery
        bulk_rename:
          - from: Battery Level
            to: ''
          - from: ' Battery'
            to: ''
        color_gradient:
          - '#ff0000'
          - '#0000ff'
          - '#00ff00'
                    
