title: The Dairy

background: radial-gradient(navy, skyblue)
# Exclude entities from "Unused entities" view
excluded_entities:
  - binary_sensor.switch_bedside
  - binary_sensor.switch_bedside_right
  - binary_sensor.wall_switch_both_bathroom
  - binary_sensor.wall_switch_left_bathroom
  - binary_sensor.wall_switch_right_bathroom
  - group.all_automations
  - group.all_devices
  - group.all_lights
  - group.all_scripts
  - group.all_switches
  - group.unassigned
  - script.sonos_play_non_matching
  - script.sonos_play_matching
  - script.sonos_ungroup_and_play
  - sensor.battery_paul
  - sensor.lastfm_cowanfamily
  - switch.plug_bedroom_left
  - switch.plug_bedroom_right
  - switch.plug_beerfridge
views:
  - title: Overview
    path: overview
    cards:
      - type: entity-filter
        entities:
          - person.paul
          - person.dorothy
          - group.kids_presence
        state_filter:
          - 'home'
        card:
          type: glance
          title: Currently home
      - type: entities
        entities:
          - binary_sensor.pet_tabitha
          - binary_sensor.pet_tamara
      - type: entities
        entities:
          - input_boolean.guest_mode
      - type: media-control
        entity: media_player.home_group
      - type: 'custom:mini-graph-card'
        name: Temperatures
        points_per_hour: 10
        entities:
          - entity: sensor.temperature_livingroom
            name: Living Room
          - entity: sensor.lilyfield_temperature
            name: Outside
        min_bound_range: 5
        show:
          labels: true
      - type: weather-forecast
        entity: weather.lilyfield
      - type: vertical-stack
        cards:
          - type: 'custom:garbage-collection-card'
            entity: sensor.rubbish
          - type: 'custom:garbage-collection-card'
            entity: sensor.garden_waste
          - type: 'custom:garbage-collection-card'
            entity: sensor.container_recycling
          - type: 'custom:garbage-collection-card'
            entity: sensor.paper_recycling
      - type: entities
        entities:
          - binary_sensor.front_door_open
          - lock.front_door
          - sensor.front_door_operator


  - title: Living Room
    icon: mdi:sofa
    path: living
    cards:
      - type: 'custom:simple-thermostat'
        entity: climate.living_room
        layout:
          mode:
            headings: false
            icons: true
            names: true
          step: row
        sensors:
          - entity: sensor.humidity_livingroom
            name: Humidity
      - type: vertical-stack
        cards:
        - type: light
          entity: light.yeelight_livingroom
          name: Living Room Light
        - type: entities
          entities:
          - type: 'custom:rgb-light-card'
            entity: light.yeelight_livingroom
            colors: !include flux_colors.yaml
          - type: 'custom:slider-entity-row'
            entity: light.yeelight_livingroom
            toggle: true
      - type: 'custom:mini-media-player'
        entity: media_player.living_room
        hide:
          icon: true
          power: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities: !include sonos-speakers.yaml
        artwork: cover
      - type: media-control
        entity: media_player.living_room_tv
      - type: media-control
        entity: media_player.receiver
      - type: media-control
        entity: media_player.living_room_sonos_cast
      - type: 'custom:mini-graph-card'
        name: Living Room Climate
        points_per_hour: 20
        entities:
          - entity: sensor.temperature_livingroom
            name: Temperature
          - entity: sensor.humidity_livingroom
            name: Humidity
            y_axis: secondary
        min_bound_range: 5
        min_bound_range_secondary: 2
        show:
          labels: true
          labels_secondary: true

  - title: Kitchen
    icon: mdi:fridge-outline
    path: kitchen
    cards:
      - type: 'custom:mini-media-player'
        entity: media_player.kitchen
        hide:
          icon: true
          power: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities: !include sonos-speakers.yaml
        artwork: cover
      - type: entities
        entities:
        - switch.diffuser_fan
        - light.diffuser_light
  - title: Bedroom
    icon: mdi:bed-empty
    path: bedroom
    cards:
      - type: 'custom:mini-media-player'
        entity: media_player.master_bedroom
        hide:
          icon: true
          power: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities: !include sonos-speakers.yaml
        artwork: cover
      - type: media-control
        entity: media_player.master_bedroom_mini
      - type: horizontal-stack
        cards:
        - type: entities
          show_header_toggle: false
          entities:
          - entity: light.bedside_lamps
          - type: 'custom:rgb-light-card'
            entity: light.bedside_lamps
            colors:
              - rgb_color:
                  - 255
                  - 255
                  - 255
                brightness: 100
                transition: 1
              - rgb_color:
                  - 234
                  - 136
                  - 140
                brightness: 255
                transition: 1
              - rgb_color:
                  - 251
                  - 180
                  - 139
                brightness: 200
                transition: 1
              - rgb_color:
                  - 136
                  - 198
                  - 237
                brightness: 150
                transition: 1
              - rgb_color:
                  - 140
                  - 231
                  - 185
                brightness: 100
                transition: 1

      - type: entities
        entities:
          - sun.sun
          - binary_sensor.motion_sensor_bedroom
  - title: Outside
    icon: mdi:pine-tree
    path: outside
    cards:
      - type: 'custom:sun-card'
      - type: weather-forecast
        entity: weather.lilyfield
      - type: picture-entity
        entity: camera.sydney_weather_radar
        show_state: false
      - type: horizontal-stack
        cards:
        - type: 'custom:compass-card'
          indicator_sensors:
            - sensor: sensor.sydney_observatory_hill_wind_direction
              indicator:
                type: arrow_inward
          value_sensors:
            - sensor: sensor.sydney_observatory_hill_wind_speed_kilometre
          compass:
            north:
              show: true
        - type: glance
          entities:
            - sensor.moon
      - type: 'custom:mini-media-player'
        entity: media_player.outside
        hide:
          icon: true
          power: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities: !include sonos-speakers.yaml
        artwork: cover
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
          - type: sensor
            entity: sensor.temperature_beerfridge
            detail: 2
            graph: line
          - type: sensor
            entity: sensor.beerfridge_power
            graph: line
            detail: 2
            icon: mdi:flash
      - type: 'custom:simple-thermostat'
        entity: climate.beer_fridge
        header:
          icon: 'mdi:fridge'
        layout:
          step: row
        step_size: '0.5'
        sensors:
          - entity: sensor.humidity_beerfridge
            name: Humidity
          - entity: sensor.beerfridge_power
            name: Power
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.outside_globes
          - type: vertical-stack
            cards:
            - type: light
              entity: light.flux_fairy
              name: Fairy Lights
            - type: 'custom:rgb-light-card'
              entity: light.flux_fairy
              colors: !include flux_colors.yaml
          - type: vertical-stack
            cards:
            - type: light
              entity: light.flux_party
              name: Party Lights
            - type: 'custom:rgb-light-card'
              entity: light.flux_party
              colors: !include flux_colors.yaml
      - type: 'custom:mini-graph-card'
        name: BBQ Cooking
        points_per_hour: 60
        entities:
          - entity: sensor.temperature_bbq_probe_1
            name: Lower (1)
            show_state: true
            state_adaptive_color: true
          - entity: sensor.temperature_bbq_probe_2
            name: Upper (2)
            show_state: true
            state_adaptive_color: true
          - entity: sensor.temperature_bbq_probe_3
            name: 3
            show_state: true
            state_adaptive_color: true
          - entity: sensor.temperature_bbq_probe_4
            name: 4
            show_state: true
            state_adaptive_color: true
          - entity: sensor.temperature_bbq_probe_5
            name: 5
            show_state: true
            state_adaptive_color: true
          - entity: sensor.temperature_bbq_probe_6
            name: 6
            show_state: true
            state_adaptive_color: true
        min_bound_range: 5
        min_bound_range_secondary: 2
        show:
          labels: false
          state: true
          legend: false
      - type: gauge
        entity: sensor.waqi_rozelle_sydney_east
        min: 0
        max: 300
        severity:
          green: 0
          yellow: 50
          red: 100
        name: Air Quality Rozelle

  - title: Bathroom
    icon: mdi:shower
    path: bathroom
    cards:
      - type: 'custom:mini-media-player'
        entity: media_player.bathroom
        hide:
          icon: true
          power: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities: !include sonos-speakers.yaml
        artwork: cover
      - type: media-control
        entity: media_player.bathroom_display
      - type: entity-button
        entity: script.shower_paul
  - title: Guest room
    icon: mdi:bunk-bed
    path: guest
    cards:
      - type: 'custom:mini-media-player'
        entity: media_player.guest_room
        hide:
          icon: true
          power: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities: !include sonos-speakers.yaml
        artwork: cover
      - type: vertical-stack
        cards:
        - type: light
          entity: light.yeelight_guestroom
          name: Guest Room Light
        - type: entities
          entities:
          - type: 'custom:slider-entity-row'
            entity: light.yeelight_guestroom
            full_row: true
          - type: 'custom:slider-entity-row'
            entity: light.yeelight_guestroom
            attribute: color_temp
            name: Color Temp
            icon: none
          - type: 'custom:rgb-light-card'
            entity: light.yeelight_guestroom
            colors: !include flux_colors.yaml
      - type: horizontal-stack
        cards:
        - type: light
          entity: light.guest_room_right
        - type: light
          entity: light.gateway_light
      - type: sensor
        entity: sensor.illumination_gateway
        graph: line
  - title: Paul Office
    icon: mdi:desk
    path: office
    cards:
      - type: 'custom:mini-media-player'
        entity: media_player.office
        hide:
          icon: true
          power: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities: !include sonos-speakers.yaml
        artwork: cover
      - type: vertical-stack
        cards:
        - type: light
          entity: light.yeelight_office
          name: Office Light
        - type: entities
          entities:
          - type: 'custom:rgb-light-card'
            entity: light.yeelight_office
            colors: !include flux_colors.yaml
      - type: entities
        entities:
        - switch.diffuser_fan_2
        - light.diffuser_light_2
      - type: gauge
        entity:
          - sensor.pixel_4_xl_battery_level
  - title: Dot Office
    icon: mdi:chair-rolling
    path: dot
    cards:
      - type: 'custom:mini-media-player'
        entity: media_player.bathroom
        hide:
          icon: true
          power: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities: !include sonos-speakers.yaml
        artwork: cover
  - title: Configuration
    icon: mdi:cog
    path: settings
    cards:
      - type: entities
        title: Individual Lights
        entities:
          - light.bedside_left
          - light.bedside_right
      - type: glance
        title: Automation Triggers
        entities:
          - automation.bedside_button
          - automation.bedside_button_double_click
          - automation.paul_arrive_home
          - automation.paul_leave_home
          - automation.paul_bathroom_button
      - type: glance
        title: Device Trackers
        entities:
          - device_tracker.paul_coral
          # - device_tracker.google_maps_107519494119268402848
          - device_tracker.oppof1s
          - device_tracker.galaxys7a
          - device_tracker.pixel
          - device_tracker.dotties_iphone
      - type: 'custom:browser-player'
      - type: glance
        title: Power
        icon: mdi:flash
        entities:
          - sensor.bedroom_left_power
          - sensor.bedroom_left_power_consumed
          - sensor.bedroom_right_power
          - sensor.bedroom_right_power_consumed
          - sensor.beerfridge_power
          - sensor.beerfridge_power_consumed
      - type: 'custom:battery-state-card'
        title: Battery State
        sort_by_level: asc
        tap_action: more-info
        filter:
          include:
            - name: entity_id
              value: '*_battery_level'
            - name: attributes.device_class
              value: battery
        bulk_rename:
          - from: Battery Level
            to: ''
          - from: ' Battery'
            to: ''
        color_gradient:
          - '#ff0000'
          - '#0000ff'
          - '#00ff00'
                    
